"""Initial migration111.

Revision ID: 05b849a8d65a
Revises: ef46025b95f9
Create Date: 2025-08-21 11:53:25.800815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b849a8d65a'
down_revision = 'ef46025b95f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requested_sugar', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('requested_oil', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('approved_sugar', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_oil', sa.Integer(), nullable=True))
        batch_op.drop_column('oil_kg')
        batch_op.drop_column('sugar_kg')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sugar_kg', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('oil_kg', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('approved_oil')
        batch_op.drop_column('approved_sugar')
        batch_op.drop_column('requested_oil')
        batch_op.drop_column('requested_sugar')

    # ### end Alembic commands ###
