"""officers-type-added-for-flying-and-more

Revision ID: 1a29c3214bcd
Revises: 40c986eda514
Create Date: 2025-10-30 10:50:52.129569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a29c3214bcd'
down_revision = '40c986eda514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_demands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('officer_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('total_days_available', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_demands', schema=None) as batch_op:
        batch_op.drop_column('total_days_available')
        batch_op.drop_column('officer_type')

    # ### end Alembic commands ###
