"""raiser1

Revision ID: 37f025aa2895
Revises: 488772f035d6
Create Date: 2025-09-11 07:24:52.110680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f025aa2895'
down_revision = '488772f035d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_demands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('availability_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('created_by', sa.String(length=20), nullable=True))
        batch_op.alter_column('employee_number',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('ration_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('office_phone',
               existing_type=sa.VARCHAR(length=5),
               type_=sa.String(length=10),
               nullable=True)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('collection_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('ifsc',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('rik_gx_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('rik_gx_date',
               existing_type=sa.DATE(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_demands', schema=None) as batch_op:
        batch_op.alter_column('rik_gx_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('rik_gx_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('ifsc',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('bank_account',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('collection_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('office_phone',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=5),
               nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('ration_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('employee_number',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('created_by')
        batch_op.drop_column('availability_days')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
