"""issuer1

Revision ID: 40c986eda514
Revises: f7644d8c5c02
Create Date: 2025-09-24 10:01:29.385940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40c986eda514'
down_revision = 'f7644d8c5c02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raised_demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer_demand_id', sa.Integer(), nullable=False),
    sa.Column('raiser_id', sa.String(length=50), nullable=False),
    sa.Column('demand_type', sa.String(length=20), nullable=False),
    sa.Column('availability_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['officer_demand_id'], ['officer_demands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raised_demands')
    # ### end Alembic commands ###
