"""initial schema

Revision ID: 40def1faba74
Revises: 
Create Date: 2025-09-04 10:31:52.666190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40def1faba74'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requested_sugar', sa.Integer(), nullable=False),
    sa.Column('requested_oil', sa.Integer(), nullable=False),
    sa.Column('approved_sugar', sa.Integer(), nullable=True),
    sa.Column('approved_oil', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('employee_code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demand')
    # ### end Alembic commands ###
