"""officer_form

Revision ID: 488772f035d6
Revises: 6c0deaecb9dd
Create Date: 2025-09-10 09:36:31.675975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488772f035d6'
down_revision = '6c0deaecb9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('officer_demands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_number', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.String(length=50), nullable=False),
    sa.Column('ration_type', sa.String(length=10), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=100), nullable=False),
    sa.Column('office_phone', sa.String(length=5), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('collection_type', sa.String(length=50), nullable=False),
    sa.Column('bank_account', sa.String(length=30), nullable=False),
    sa.Column('ifsc', sa.String(length=20), nullable=False),
    sa.Column('rik_gx_number', sa.String(length=50), nullable=False),
    sa.Column('rik_gx_date', sa.Date(), nullable=False),
    sa.Column('rik_gx_file', sa.String(length=200), nullable=True),
    sa.Column('retirement_date', sa.Date(), nullable=True),
    sa.Column('promotion_gx_number', sa.String(length=50), nullable=True),
    sa.Column('promotion_gx_date', sa.Date(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('officer_demands')
    # ### end Alembic commands ###
