"""raiser_offic

Revision ID: e1363bbbf1ba
Revises: 37f025aa2895
Create Date: 2025-09-12 05:22:10.952734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1363bbbf1ba'
down_revision = '37f025aa2895'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_demands', schema=None) as batch_op:
        batch_op.alter_column('employee_number',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('ration_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('office_phone',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=False)
        batch_op.alter_column('collection_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('bank_account',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.alter_column('ifsc',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('rik_gx_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('rik_gx_date',
               existing_type=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_demands', schema=None) as batch_op:
        batch_op.alter_column('rik_gx_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('rik_gx_number',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('ifsc',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('bank_account',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
        batch_op.alter_column('collection_type',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('mobile',
               existing_type=sa.VARCHAR(length=15),
               nullable=True)
        batch_op.alter_column('office_phone',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('unit',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('address',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('ration_type',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('rank',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('employee_number',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###
