"""3issue-tabs

Revision ID: f7644d8c5c02
Revises: e1363bbbf1ba
Create Date: 2025-09-24 05:57:45.246410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7644d8c5c02'
down_revision = 'e1363bbbf1ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_demands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_first15', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('availability_second15', sa.Integer(), nullable=True))
        batch_op.drop_column('availability_days')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('officer_demands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('availability_second15')
        batch_op.drop_column('availability_first15')

    # ### end Alembic commands ###
